name = "al-dalil-ai-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# AI binding for Cloudflare Workers AI
[ai]
binding = "AI"

# Add environment variables for AI access
[vars]
ENVIRONMENT = "production"

# Add necessary permissions
[env.production]
compatibility_date = "2024-01-01"

# Ensure AI models are accessible
[[ai.models]]
name = "@cf/black-forest-labs/flux-1-schnell"

[[ai.models]]
name = "@cf/meta/m2m100-1.2b"

[[ai.models]]
name = "@cf/myshell-ai/melotts"

[[ai.models]]
name = "@cf/stabilityai/stable-diffusion-xl-base-1.0"

[[ai.models]]
name = "@cf/stabilityai/sdxl-lightning"

[[ai.models]]
name = "@cf/stabilityai/dreamshaper-8-lcm"

[[ai.models]]
name = "@cf/meta/llama-2-7b-chat-int8"

[[ai.models]]
name = "@cf/openai/gpt-oss-120b"

[[ai.models]]
name = "@cf/meta/llama-guard-3-8b"

[[ai.models]]
name = "@cf/mistralai/mistral-7b-instruct-v0.1"

[[ai.models]]
name = "@cf/meta/llama-3.3-70b-instruct-fp8-fast"

[[ai.models]]
name = "@cf/qwen/qwen2.5-coder-32b-instruct"

[[ai.models]]
name = "@cf/qwen/qwq-32b"

[[ai.models]]
name = "@cf/google/gemma-3-12b-it"

[[ai.models]]
name = "@cf/meta/llama-vision-3.2"

[[ai.models]]
name = "@cf/baai/bge-small-en-v1.5"

[[ai.models]]
name = "@cf/baai/bge-base-en-v1.5"

[[ai.models]]
name = "@cf/baai/bge-large-en-v1.5"

[[ai.models]]
name = "@cf/baai/bge-m3"

[[ai.models]]
name = "@cf/microsoft/llava-1.5-7b"

[[ai.models]]
name = "@cf/facebook/bart-large-cnn"
